version: "2"
services:
   web:
      image: w3serv/ubuntu:apache
      restart: on-failure
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /home/localadmin/docker/var/www/:/var/www/html/
